### ISSUE TITLE
Spring Cloud Consul Config

### ISSUE THREAD

**Issue by mi2shiii** [Book-Microservices-v2/update-2.4.0#1]
In page 351 in the book, you said after enabling the profiles we will see these logs:

INFO 52274 --- [main] b.c.PropertySourceBootstrapConfiguration : Located
property source: [BootstrapPropertySource {name='bootstrapProperties-
config/**multiplication**,rabbitmq-production/'}, BootstrapPropertySource
{name='bootstrapProperties-config/**multiplication**,production/'},
BootstrapPropertySource {name='bootstrapProperties-config/**multiplication**/'},
BootstrapPropertySource {name='bootstrapProperties-config/defaults,rabbitmq-
production/'}, BootstrapPropertySource {name='bootstrapProperties-config/
defaults,production/'}, BootstrapPropertySource {name='bootstrapProperties-config/
defaults/'}]

But for me it shows:
2021-04-02 22:11:48.023  INFO [,,] 1292 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-config/**application**,rabbitmq-production/'}, BootstrapPropertySource {name='bootstrapProperties-config/**application**,production/'}, BootstrapPropertySource {name='bootstrapProperties-config/**application**/'}, BootstrapPropertySource {name='bootstrapProperties-config/defaults,rabbitmq-production/'}, BootstrapPropertySource {name='bootstrapProperties-config/defaults,production/'}, BootstrapPropertySource {name='bootstrapProperties-config/defaults/'}]

The difference is the name of the application ( Multiplication here ) is not appeared in my log and it is instead: application.

**Comment by mi2shiii** [comment]
Therefore, the page 353 for multiplication,production can not be applied. It also didn't works for application,production.

**Comment by mechero** [comment]
Hi @mi2shiii, thanks for reporting this! I'll check this in the coming days. Just to make sure, are you using exactly the same code as in this repository?

**Comment by mi2shiii** [comment]
Yes exactly the same code :)

**Comment by mechero** [comment]
OK I found the issue, it's only happening after the upgrade to Spring Boot 2.4.0. These are the logs after running the `multiplication` microservice from this repo vs [chapter08d](https://github.com/Book-Microservices-v2/chapter08d):

```
:: Spring Boot ::                (v2.4.0)

2021-04-08 07:39:52.904  INFO [,,] 37261 --- [           main] b.c.PropertySourceBootstrapConfiguration : 
Located property source: [BootstrapPropertySource {name='bootstrapProperties-config/application,rabbitmq-production/'}, 
BootstrapPropertySource {name='bootstrapProperties-config/application,production/'}, BootstrapPropertySource 
{name='bootstrapProperties-config/application/'}, BootstrapPropertySource {name='bootstrapProperties-
config/defaults,rabbitmq-production/'}, BootstrapPropertySource {name='bootstrapProperties-config/defaults,production/'},
 BootstrapPropertySource {name='bootstrapProperties-config/defaults/'}]

:: Spring Boot ::        (v2.3.3.RELEASE)

2021-04-08 07:39:12.100  INFO [,,,] 37053 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property
 source: [BootstrapPropertySource {name='bootstrapProperties-config/multiplication,rabbitmq-production/'}, 
BootstrapPropertySource {name='bootstrapProperties-config/multiplication,production/'}, BootstrapPropertySource 
{name='bootstrapProperties-config/multiplication/'}, BootstrapPropertySource {name='bootstrapProperties-
config/defaults,rabbitmq-production/'}, BootstrapPropertySource {name='bootstrapProperties-config/defaults,production/'}, 
BootstrapPropertySource {name='bootstrapProperties-config/defaults/'}]
```

I'll try to dive into the docs to see if this is a new intended behavior or not. It might be caused by the changes they made to the bootstrap phase; basically they want to get rid of it, so this could have led to incompatibilities.

For now, if you want to reproduce the steps as detailed in the book, please use the code from chapter08d.

**Comment by mechero** [comment]
The PR #5 fixes this issue. I moved the `spring.application.name` property to the bootstrap configuration for better compatibility.

**Comment by mechero** [comment]
It should work now if you pull the latest changes. Thanks!
