### ISSUE TITLE
Traceability doesn't work properly

### ISSUE THREAD

**Issue by mi2shiii** [Book-Microservices-v2/update-2.4.0#2]
I can not get a unique trace id as you mentioned in page 372.

These are my logs after running: 
 http POST :8000/attempts factorA=15 factorB=20 userAlias=test-user-tracing2 guess=300

:

[multiplication ] [a8f7d566961120a2,91d2007df42cab2a] INFO  01:44:07.426 [http-nio-9080-exec-7] m.b.m.c.ChallengeAttemptController - Received new attempt from test-user-tracing
[multiplication ] [9cf85d44846167d9,42dd652a2280836b] INFO  01:44:07.454 [http-nio-9080-exec-7] m.b.m.challenge.ChallengeServiceImpl - Creating new user with alias test-user-tracing
[gamification   ] [55609da987fbc5fe,80c7a0eea2227cf6] INFO  01:44:07.554 [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#0-8] m.b.g.game.GameEventHandler - Challenge Solved Event received: 91
[gamification   ] [51ad8b9ba5ece336,2ce29aa8ad225af6] INFO  01:44:07.616 [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#0-8] m.b.g.game.GameServiceImpl - User test-user-tracing scored 10 points for attempt id 91

another run:

[multiplication ] [7ded9681ed7dcdbf,6ec8801e347c1cad] INFO  01:45:27.154 [http-nio-8080-exec-3] m.b.m.c.ChallengeAttemptController - Received new attempt from test-user-tracing
[gamification   ] [361a49142e9fdedd,0a132ba5603e4eb6] INFO  01:45:27.253 [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#0-14] m.b.g.game.GameEventHandler - Challenge Solved Event received: 92
[gamification   ] [caccce366cf718ef,8ab1918f27b366b6] INFO  01:45:27.307 [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#0-14] m.b.g.game.GameServiceImpl - User test-user-tracing scored 10 points for attempt id 92

**Comment by mechero** [comment]
Thanks for reporting this! I created PR #4 that fixes this issue, you can find more details in the description.

I'll modify the blog post accordingly, will link to your issue as a way to say thanks 😄

**Comment by mi2shiii** [comment]
Thanks.
